/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 86xkvA5Bvu8CnDW9huPe8b

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 86xkvA5Bvu8CnDW9huPe8b/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: 86xkvA5Bvu8CnDW9huPe8b/projectcss

import plasmic_library_tailwind_3_4_colors_css from "../library_tailwind_3_4_color_tokens/plasmic.module.css"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss

const data = {
  base: `${projectcss.plasmic_tokens} ${plasmic_library_tailwind_3_4_colors_css.plasmic_tokens} ${plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens} ${plasmic_antd_5_hostless_css.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
