/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 86xkvA5Bvu8CnDW9huPe8b

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: bt1eia75QBDb/globalVariant
import {
  UnnamedGlobalGroupOfVariantsValue,
  useUnnamedGlobalGroupOfVariants
} from "./PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants"; // plasmic-import: 0WnOSpRT8XST/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  theme: useTheme,
  unnamedGlobalGroupOfVariants: useUnnamedGlobalGroupOfVariants
});
